#ifndef COOPERATIVEEXPLORATIONSIMULATION_CELLSTATE_H
#define COOPERATIVEEXPLORATIONSIMULATION_CELLSTATE_H

enum class CellState
{
    Unknown,
    Free,
    Obstacle,
    OccupiedByAgent,
};

#endif //COOPERATIVEEXPLORATIONSIMULATION_CELLSTATE_H
